services:
  db:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: kedarnath
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  kedarnath-api:
    container_name: kedarnath-api
    image: dkedarnath/kedarnath-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  kedarnath-react:
    container_name: kedarnath-react
    image: dkedarnath/kedarnath-react
    build:
      context: frontend/react
      args:
        api_base_url: http://kedarnath-api:8088
    ports:
      - "3000:5173"
    depends_on:
      - kedarnath-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

